image: node:10.15.3

stages:
  - build
  - review
  - develop
  - staging
  - production

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules/

before_script:
  - apt-get update -y && apt-get install rsync wget unzip -y
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

build_prod:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour
  script:
   - cd website
   - yarn install --pure-lockfile --cache-folder .yarn
   - yarn run build
  only:
    - master
  tags:
    - docker

build_dev:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour
  script:
   - cd website
   - yarn install --pure-lockfile --cache-folder .yarn
   - yarn run build
  except:
    - master
  tags:
    - docker

review:
  stage: review
  script:
    - rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./website/build/galtproject-docs $GS_DEPLOY_USER@$GS_DEPLOY_HOST:$GS_DEPLOY_PATH/review/$CI_BUILD_REF_SLUG
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_BUILD_REF_SLUG.docs.galtproject.io
    on_stop: stop_review
  only:
    - branches
  except:
    - master
    - develop
  tags:
    - docker

stop_review:
  stage: review
  script:
    - rm -rf ./dist/*
    - rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./website/build/galtproject-docs $GS_DEPLOY_USER@$GS_DEPLOY_HOST:$GS_DEPLOY_PATH/review/$CI_BUILD_REF_SLUG
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  except:
    - master
    - develop
  tags:
    - docker

develop:
  stage: develop
  script:
   - rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./website/build/galtproject-docs $GS_DEPLOY_USER@$GS_DEPLOY_HOST:$GS_DEPLOY_PATH/develop
  environment:
    name: develop
    url: https://develop.docs.galtproject.io
  only:
   - develop
  tags:
    - docker

staging:
  stage: staging
  script:
   - rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./website/build/galtproject-docs $GS_DEPLOY_USER@$GS_DEPLOY_HOST:$GS_DEPLOY_PATH/staging
  environment:
    name: staging
    url: https://staging.docs.galtproject.io
  only:
   - master
  tags:
    - docker

production:
  stage: production
  script:
    - ssh -o StrictHostKeyChecking=no $GS_DEPLOY_USER@$GS_DEPLOY_HOST "rsync -avz --delete $GS_DEPLOY_PATH/staging/* $GS_DEPLOY_PATH/production"
  environment:
    name: production
    url: https://docs.galtproject.io
  when: manual
  only:
    - master
  tags:
    - docker
